name: release-single-app

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm i

      - name: 前端项目打包
        run: pnpm -r run build

      - name: 构建&上传镜像
        run: | 
          echo "准备构建镜像：module-federation-demo:single-app"
          docker login ccr.ccs.tencentyun.com --username=${{ secrets.TENCENT_DCOKERHUB_USERNAME }} --password=${{ secrets.TENCENT_DCOKERHUB_PASSWORD }}
          docker version
          docker build -f Dockerfile -t ccr.ccs.tencentyun.com/yb_study/module-federation-demo:single-app .
          docker push ccr.ccs.tencentyun.com/yb_study/module-federation-demo:single-app
          
      - name: 重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_SERVER_HOST }}
          username: ${{ secrets.TENCENT_SERVER_USERNAME }}
          key: ${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.TENCENT_SERVER_SSH_PORT }}
          script: |
            cd /www/
            docker compose pull mf-single-app-demo
            docker compose up -d

